# Nombre de la aplicación
spring.application.name=ProyectoSpendy

# Configuración de Base de Datos H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:spendydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto crea automáticamente las tablas basadas en tus @Entity
spring.jpa.hibernate.ddl-auto=update

# Permite ver la consola de la base de datos en el navegador (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console